name: Auto create PR to format source

on:
  create:
    branches:
      - format/main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Auto format source'
          body: 'This PR is automatically created to format the source code.'
          base: main
          branch: format/main
