name: Format source

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Format source
        run: |
          pnpm i
          pnpm run format

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'fix: format source'
